### ISSUE TITLE
[Bug]: FLUX models not working (in Stability Matrix) - KeyError: 'model.diffusion_model.input_blocks.0.0.weight

### ISSUE THREAD

**Issue by fbauer-kunbus** [mashb1t/Fooocus#88]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I installed this fork of Fooocus explicitly in 'Stability Matrix' because it was said to support Flux models - but none of my existing Flux models work - all give me the error 'KeyError: 'model.diffusion_model.input_blocks.0.0.weight' immediately after clicking 'Generate'

### Steps to reproduce the problem

Just load any of the common Flux models and try to generate an image; models tried: dev / schnell / nf4

### What should have happened?

Fooocus should create an image using Flux model

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\modules\async_worker.py", line 1483, in worker
    handler(task)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\modules\async_worker.py", line 1172, in handler
    tasks, use_expansion, loras, current_progress = process_prompt(async_task, async_task.prompt, async_task.negative_prompt,
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\modules\async_worker.py", line 662, in process_prompt
    pipeline.refresh_everything(refiner_model_name=async_task.refiner_model_name,
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\modules\default_pipeline.py", line 250, in refresh_everything
    refresh_base_model(base_model_name, vae_name)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\modules\default_pipeline.py", line 74, in refresh_base_model
    model_base = core.load_model(filename, vae_filename)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\modules\core.py", line 147, in load_model
    unet, clip, vae, vae_filename, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=path_embeddings,
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\ldm_patched\modules\sd.py", line 449, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\ldm_patched\modules\model_detection.py", line 163, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
  File "C:\MyProg\StabilityMatrix\Data\Packages\Fooocus - mashb1t's 1-Up Edition\ldm_patched\modules\model_detection.py", line 49, in detect_unet_config
    model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
KeyError: 'model.diffusion_model.input_blocks.0.0.weight'
```

**Comment by ILikeToasters** [comment]
This fork does not claim to support Flux. I think you have it confused with SimpleSDXL which is offered in Stability Matrix as well and does support Flux.

**Comment by fbauer-kunbus** [comment]
Ok, there must have been a misunderstanding - I am quite sure I read somewhere that Flux is supported, since there is momentarily no other reason why I would have installed this fork. Ticket can be closed then.
